Repository OCA/dms, pull requests merged in 2020-10, with the labels that each got.

#22 [12.0][IMP] dms: Portal
  dms/__manifest__.py
  dms/controllers/__init__.py
  dms/controllers/portal.py
  dms/demo/access_group.xml
  dms/demo/assets.xml
  dms/demo/directory.xml
  dms/i18n/dms.pot
  dms/models/directory.py
  dms/models/dms_file.py
  dms/readme/CONTRIBUTORS.rst
  dms/readme/DESCRIPTION.rst
  dms/readme/ROADMAP.rst
  dms/readme/USAGE.rst
  dms/security/ir.model.access.csv
  dms/static/src/js/dms_portal_tour.js
  dms/tests/__init__.py
  dms/tests/test_portal.py
  dms/views/directory.xml
  dms/views/dms_file.xml
  dms/views/dms_portal_templates.xml
Labels: bot is merging ⏳

#26 [12.0][FIX] dms: Change share_url in dms_directory
  dms/controllers/portal.py
  dms/models/directory.py
  dms/models/dms_file.py
  dms/models/dms_security_mixin.py
  dms/security/ir.model.access.csv
  dms/views/dms_portal_templates.xml
Labels: approved, bot is merging ⏳

#25 [13.0][IMP] dms: Portal
  dms/__manifest__.py
  dms/controllers/__init__.py
  dms/controllers/portal.py
  dms/demo/access_group.xml
  dms/demo/assets.xml
  dms/demo/directory.xml
  dms/i18n/dms.pot
  dms/models/directory.py
  dms/models/dms_file.py
  dms/models/dms_security_mixin.py
  dms/readme/CONTRIBUTORS.rst
  dms/readme/DESCRIPTION.rst
  dms/readme/ROADMAP.rst
  dms/readme/USAGE.rst
  dms/security/ir.model.access.csv
  dms/static/src/js/dms_portal_tour.js
  dms/tests/__init__.py
  dms/tests/test_portal.py
  dms/views/directory.xml
  dms/views/dms_file.xml
  dms/views/dms_portal_templates.xml
Labels: bot is merging ⏳

#20 [IMP] dms: Integrate with mail_preview_base
  dms/README.rst
  dms/__manifest__.py
  dms/readme/INSTALL.rst
  dms/static/description/index.html
  dms/static/src/js/fields/preview.js
  dms/static/src/scss/preview.scss
  dms/template/assets.xml
  oca_dependencies.txt
Labels: approved, bot is merging ⏳, ready to merge

#34 [FIX] dms: custom thumbnail was not correctly computed
  dms/models/mixins_thumbnail.py
Labels: approved, bot is merging ⏳

#29 [12.0][FIX] dms: /my/dms change to user and separate some urls in some functions
  dms/controllers/portal.py
  dms/static/src/js/dms_portal_tour.js
  dms/views/dms_portal_templates.xml
Labels: bot is merging ⏳

#30 [13.0][FIX] dms: /my/dms change to user and separate some urls in some functions
  dms/controllers/portal.py
  dms/static/src/js/dms_portal_tour.js
  dms/views/dms_portal_templates.xml
Labels: bot is merging ⏳

#24 [12.0] [IMP] dms: Attachment Integration
  dms/models/__init__.py
  dms/models/directory.py
  dms/models/dms_file.py
  dms/models/ir_attachment.py
  dms/models/storage.py
  dms/readme/ROADMAP.rst
  dms/tests/common.py
  dms/tests/test_storage.py
  dms/views/directory.xml
  dms/views/dms_file.xml
  dms/views/storage.xml
Labels: approved, bot is merging ⏳
