Repository OCA/dms, pull requests merged in 2021-07, with the labels that each got.

#108 [14.0][FIX] dms: image thumbnails performance
  dms/models/directory.py
  dms/models/mixins_thumbnail.py
  dms/readme/CONTRIBUTORS.rst
  dms/static/lib/img/thumbnails/file_unknown.png
  dms/static/lib/img/thumbnails/file_unknown.svg
  dms/views/directory.xml
  dms/views/dms_file.xml
  dms/views/dms_portal_templates.xml
Labels: approved, bot is merging ⏳, ready to merge

#110 [13.0][FIX] dms: Fix multi-company rules + migration scripts
  dms/__manifest__.py
  dms/migrations/13.0.6.1.0/noupdate_changes.xml
  dms/migrations/13.0.6.1.0/post-migration.py
  dms/security/security.xml
Labels: approved, bot is merging ⏳

#111 [14.0][FIX] dms: Fix multi-company rules + migration scripts
  dms/__manifest__.py
  dms/migrations/14.0.2.1.0/noupdate_changes.xml
  dms/migrations/14.0.2.1.0/post-migration.py
  dms/security/security.xml
Labels: bot is merging ⏳

#107 [13.0][REF] dms: modify permissions computation
  dms/controllers/portal.py
  dms/demo/access_group.xml
  dms/demo/directory.xml
  dms/models/abstract_dms_mixin.py
  dms/models/access_groups.py
  dms/models/directory.py
  dms/models/dms_file.py
  dms/models/dms_security_mixin.py
  dms/models/ir_attachment.py
  dms/readme/ROADMAP.rst
  dms/security/ir.model.access.csv
  dms/security/security.xml
  dms/tests/common.py
  dms/tests/test_file.py
  dms/tests/test_file_database.py
  dms/tests/test_portal.py
  dms/tests/test_storage_attachment.py
  dms/views/directory.xml
  dms/views/dms_access_groups_views.xml
Labels: bot is merging ⏳, bug, enhancement

#112 [12.0][FIX] dms: me cases admin and demo users have previously in 'Show private access' group and causes some tests to fail.
  dms/tests/test_storage_attachment.py
Labels: approved, bot is merging ⏳

#94 [13.0][FIX] dms: Remove _get_share_url() function because is not necessary to override nothing
  dms/models/dms_file.py
Labels: approved, bot is merging ⏳

#115 [12.0][FIX] dms: Fix tests for environments that add other groups to base users
  dms/tests/test_storage_attachment.py
Labels: approved, bot is merging ⏳

#116 [13.0][FIX] dms: Fix tests for environments that add other groups to base users
  dms/tests/test_storage_attachment.py
Labels: approved, bot is merging ⏳

#113 [14.0][REF] dms: modify permissions computation
  dms/controllers/portal.py
  dms/demo/access_group.xml
  dms/demo/directory.xml
  dms/models/abstract_dms_mixin.py
  dms/models/access_groups.py
  dms/models/directory.py
  dms/models/dms_file.py
  dms/models/dms_security_mixin.py
  dms/models/ir_attachment.py
  dms/readme/ROADMAP.rst
  dms/security/ir.model.access.csv
  dms/security/security.xml
  dms/tests/common.py
  dms/tests/test_file.py
  dms/tests/test_file_database.py
  dms/tests/test_portal.py
  dms/tests/test_storage_attachment.py
  dms/views/directory.xml
  dms/views/dms_access_groups_views.xml
Labels: approved, bot is merging ⏳, bug, enhancement, needs review, ready to merge

#117 [13.0][IMP+FIX] dms: Changes in file tree view + Fix file preview.
  dms/models/dms_file.py
  dms/static/src/js/fields/path.js
  dms/static/src/js/views/search_panel.js
  dms/template/assets.xml
  dms/tests/test_file.py
  dms/views/dms_file.xml
Labels: approved, bot is merging ⏳, ready to merge

#127 [13.0][IMP] dms: Forgotten migration script related to https://github.com/OCA/dms/commit/0ae10d1714d806bb806c16796204e610b6c1a777 is added
  dms/__manifest__.py
  dms/migrations/13.0.8.1.0/post-migration.py
Labels: approved, bot is merging ⏳
