Repository OCA/dms, pull requests merged in 2021-02, with the labels that each got.

#51 [12.0][FIX] dms: Fix error when web_drop_target addon used to create new file + remove content field in tree
  dms/models/dms_file.py
  dms/views/dms_file.xml
Labels: approved, bot is merging ⏳

#52 [13.0][FIX] dms: Fix error when web_drop_target addon used to create new file + remove content field in tree
  dms/models/dms_file.py
  dms/views/dms_file.xml
Labels: approved, bot is merging ⏳

#55 [IMP] dms: Integrate with mail_preview_base
  dms/README.rst
  dms/__manifest__.py
  dms/readme/INSTALL.rst
  dms/static/description/index.html
  dms/static/src/js/fields/preview.js
  dms/static/src/js/views/file_kanban_controller.js
  dms/static/src/scss/preview.scss
  dms/template/assets.xml
  oca_dependencies.txt
Labels: approved, bot is merging ⏳

#54 [12.0][FIX] dms: Kanban view
  dms/static/src/js/views/file_kanban_controller.js
Labels: approved, bot is merging ⏳

#56 [12.0][FIX] dms: Remove category creation in kanban tag view to prevent error
  dms/views/tag.xml
Labels: approved, bot is merging ⏳

#57 [13.0][FIX] dms: Remove category creation in kanban tag view to prevent error
  dms/views/tag.xml
Labels: bot is merging ⏳

#53 [12.0][FIX] dms: Use sudo() in attachment operacion to prevent error in attachment creation
  dms/models/ir_attachment.py
  dms/tests/__init__.py
  dms/tests/test_ir_attachment.py
Labels: approved, bot is merging ⏳, ready to merge

#63 [12.0][FIX] dms_field: Change sequence value to prevent appear first in dms app
  dms_field/views/dms_storage.xml
Labels: bot is merging ⏳

#64 [13.0][FIX] dms: Prevent error when change name or content
  dms/models/dms_file.py
Labels: approved, bot is merging ⏳
