Repository OCA/dms, pull requests merged in 2021-06, with the labels that each got.

#95 [14.0][FIX] dms: Improve tests (prevent error if installed other addons after dms install and new addons auto-create partners)
  dms/tests/test_storage_attachment.py
Labels: approved, bot is merging ⏳

#96 [14.0][FIX] dms: Apply _apply_access_groups correctly (specially according to files) to get only records to get only allowed records according to directories groups
  dms/models/dms_security_mixin.py
  dms/tests/test_file.py
Labels: approved, bot is merging ⏳

#88 [FIX] dms: image thumbnails performance
  dms/__manifest__.py
  dms/migrations/12.0.6.0.0/post-migration.py
  dms/models/directory.py
  dms/models/mixins_thumbnail.py
  dms/readme/CONTRIBUTORS.rst
  dms/static/lib/img/thumbnails/file_unknown.png
  dms/static/lib/img/thumbnails/file_unknown.svg
  dms/views/directory.xml
  dms/views/dms_file.xml
  dms/views/dms_portal_templates.xml
Labels: approved, bot is merging ⏳

#100 [FIX] dms: cascade removal of related files/directories
  dms/models/__init__.py
  dms/models/base.py
  dms/tests/test_storage_attachment.py
Labels: approved, bot is merging ⏳

#103 [13.0][FIX] dms: cascade removal of related files/directories
  dms/models/__init__.py
  dms/models/base.py
  dms/tests/test_storage_attachment.py
Labels: bot is merging ⏳

#104 [14.0][FIX] dms: cascade removal of related files/directories
  dms/models/__init__.py
  dms/models/base.py
  dms/tests/test_storage_attachment.py
Labels: bot is merging ⏳

#97 [13.0][FIX] dms: image thumbnails performance
  dms/models/directory.py
  dms/models/mixins_thumbnail.py
  dms/readme/CONTRIBUTORS.rst
  dms/static/lib/img/thumbnails/file_unknown.png
  dms/static/lib/img/thumbnails/file_unknown.svg
  dms/views/directory.xml
  dms/views/dms_file.xml
  dms/views/dms_portal_templates.xml
Labels: approved, bot is merging ⏳

#102 [REF] dms: modify permissions computation
  dms/controllers/portal.py
  dms/demo/access_group.xml
  dms/demo/directory.xml
  dms/models/access_groups.py
  dms/models/directory.py
  dms/models/dms_file.py
  dms/models/dms_security_mixin.py
  dms/models/ir_attachment.py
  dms/readme/ROADMAP.rst
  dms/security/ir.model.access.csv
  dms/security/security.xml
  dms/tests/common.py
  dms/tests/test_directory.py
  dms/tests/test_portal.py
  dms/tests/test_storage_attachment.py
  dms/views/directory.xml
  dms/views/dms_access_groups_views.xml
Labels: approved, bot is merging ⏳, enhancement
