Repository OCA/dms, pull requests merged in 2022-05, with the labels that each got.

#167 [13.0][FIX] dms: Prevent 200 records limit in search panel.
  dms/models/abstract_dms_mixin.py
  dms/models/dms_file.py
  dms/static/src/xml/views.xml
  dms/tests/test_directory.py
Labels: bot is merging ⏳, approved, ready to merge

#180 [14.0][FIX] dms: Prevent 200 records limit in search panel.
  dms/models/abstract_dms_mixin.py
  dms/models/dms_file.py
  dms/static/src/xml/views.xml
  dms/tests/test_directory.py
Labels: bot is merging ⏳, approved

#181 Revert "[14.0][FIX] dms: Prevent 200 records limit in search panel."
  dms/models/abstract_dms_mixin.py
  dms/models/dms_file.py
  dms/static/src/xml/views.xml
  dms/tests/test_directory.py
Labels: bot is merging ⏳, needs review

#185 [13.0][FIX] dms: Apply sudo() when downloading the files (portal users do not have access to ir.attachment for example).
  dms/controllers/portal.py
Labels: bot is merging ⏳, approved
