Repository OCA/dms, pull requests merged in 2024-05, with the labels that each got.

#329 [15.0][IMP] dms_auto_classification: Add folder support within the .zip file
  dms_auto_classification/README.rst
  dms_auto_classification/readme/CONFIGURE.rst
  dms_auto_classification/readme/USAGE.rst
  dms_auto_classification/static/description/index.html
  dms_auto_classification/tests/data/test.zip
  dms_auto_classification/tests/test_dms_auto_classification.py
  dms_auto_classification/wizards/wizard_dms_classification.py
  dms_auto_classification/wizards/wizard_dms_classification_views.xml
Labels: bot is merging ⏳, approved

#331 [16.0][IMP] dms_auto_classification: Add folder support within the .zip file
  dms_auto_classification/README.rst
  dms_auto_classification/readme/CONFIGURE.rst
  dms_auto_classification/readme/USAGE.rst
  dms_auto_classification/static/description/index.html
  dms_auto_classification/tests/data/test.zip
  dms_auto_classification/tests/test_dms_auto_classification.py
  dms_auto_classification/wizards/wizard_dms_classification.py
  dms_auto_classification/wizards/wizard_dms_classification_views.xml
Labels: bot is merging ⏳, approved

#332 [16.0][FIX]dms: error when clicked the file smart button.
  dms/models/dms_file.py
Labels: bot is merging ⏳, approved

#275 [16.0][ADD] dms_storage
  dms_storage/README.rst
  dms_storage/__init__.py
  dms_storage/__manifest__.py
  dms_storage/models/__init__.py
  dms_storage/models/dms_file.py
  dms_storage/models/dms_storage.py
  dms_storage/readme/CONTRIBUTORS.rst
  dms_storage/readme/DESCRIPTION.rst
  dms_storage/static/description/icon.png
  dms_storage/static/description/index.html
  dms_storage/tests/__init__.py
  dms_storage/tests/test_storage.py
  dms_storage/views/dms_storage.xml
  setup/dms_storage/odoo/addons/dms_storage
  setup/dms_storage/setup.py
Labels: bot is merging ⏳

#335 [15.0][IMP] dms_field: Add #id from record to auto-generate access group to prevent error
  dms_field/i18n/dms_field.pot
  dms_field/i18n/es.po
  dms_field/models/dms_field_template.py
  dms_field/tests/test_dms_field.py
Labels: bot is merging ⏳, approved

#338 [16.0][FIX] dms: Remove incorrect character in maximum upload size error message
  dms/i18n/de.po
  dms/i18n/dms.pot
  dms/i18n/es.po
  dms/i18n/fr.po
  dms/i18n/he_IL.po
  dms/i18n/it.po
  dms/i18n/nl.po
  dms/i18n/pt.po
  dms/i18n/pt_BR.po
  dms/i18n/ru.po
  dms/models/dms_file.py
Labels: merged 🎉
