Repository OCA/dms, pull requests merged in 2024-02, with the labels that each got.

#287 [15.0][ADD] dms_auto_classification: New module
  dms_auto_classification/README.rst
  dms_auto_classification/__init__.py
  dms_auto_classification/__manifest__.py
  dms_auto_classification/demo/dms_classification_template_demo.xml
  dms_auto_classification/i18n/dms_auto_classification.pot
  dms_auto_classification/i18n/es.po
  dms_auto_classification/models/__init__.py
  dms_auto_classification/models/dms_classification_template.py
  dms_auto_classification/readme/CONFIGURE.rst
  dms_auto_classification/readme/CONTRIBUTORS.rst
  dms_auto_classification/readme/DESCRIPTION.rst
  dms_auto_classification/readme/USAGE.rst
  dms_auto_classification/security/ir.model.access.csv
  dms_auto_classification/security/security.xml
  dms_auto_classification/static/description/icon.png
  dms_auto_classification/static/description/icon.svg
  dms_auto_classification/static/description/index.html
  dms_auto_classification/tests/__init__.py
  dms_auto_classification/tests/data/test.zip
  dms_auto_classification/tests/test_dms_auto_classification.py
  dms_auto_classification/views/dms_classification_template_views.xml
  dms_auto_classification/wizards/__init__.py
  dms_auto_classification/wizards/wizard_dms_classification.py
  dms_auto_classification/wizards/wizard_dms_classification_views.xml
  setup/dms_auto_classification/odoo/addons/dms_auto_classification
  setup/dms_auto_classification/setup.py
Labels: bot is merging ⏳, approved, ready to merge

#292 [14.0][FIX] dms
  dms/models/dms_file.py
Labels: bot is merging ⏳, approved

#294 [15.0][FIX]dms: Avoid error when set files from directory form view
  dms/models/dms_file.py
Labels: bot is merging ⏳

#295 [16.0][FIX] dms: Avoid error when set files from directory form view
  dms/models/dms_file.py
Labels: bot is merging ⏳

#279 [15.0][ADD] hr_dms_field: New module
  dms/models/directory.py
  dms/models/dms_file.py
  dms/security/ir.model.access.csv
  dms/views/directory.xml
  dms/views/dms_file.xml
  dms/views/storage.xml
  dms_field/README.rst
  dms_field/__init__.py
  dms_field/__manifest__.py
  dms_field/demo/partner_dms.xml
  dms_field/i18n/dms_field.pot
  dms_field/i18n/es.po
  dms_field/models/__init__.py
  dms_field/models/base.py
  dms_field/models/dms_directory.py
  dms_field/models/dms_field_template.py
  dms_field/models/dms_storage.py
  dms_field/readme/CONFIGURE.rst
  dms_field/readme/ROADMAP.rst
  dms_field/readme/USAGE.rst
  dms_field/security/ir.model.access.csv
  dms_field/security/security.xml
  dms_field/static/description/index.html
  dms_field/static/src/js/base/dms_tree_controller.js
  dms_field/static/src/js/base/dms_tree_renderer.js
  dms_field/static/src/scss/preview.scss
  dms_field/static/src/xml/preview.xml
  dms_field/tests/test_dms_field.py
  dms_field/views/dms_field_template_views.xml
  dms_field/views/dms_storage.xml
  dms_field/wizards/__init__.py
  dms_field/wizards/dms_add_directory_record.py
  dms_field/wizards/dms_add_directory_record.xml
  hr_dms_field/README.rst
  hr_dms_field/__init__.py
  hr_dms_field/__manifest__.py
  hr_dms_field/demo/dms_data.xml
  hr_dms_field/i18n/es.po
  hr_dms_field/i18n/hr_dms_field.pot
  hr_dms_field/models/__init__.py
  hr_dms_field/models/dms_field_template.py
  hr_dms_field/models/hr_employee_public.py
  hr_dms_field/readme/CONFIGURE.rst
  hr_dms_field/readme/CONTRIBUTORS.rst
  hr_dms_field/readme/DESCRIPTION.rst
  hr_dms_field/readme/USAGE.rst
  hr_dms_field/static/description/icon.png
  hr_dms_field/static/description/index.html
  hr_dms_field/static/src/js/base/dms_tree_controller.js
  hr_dms_field/tests/__init__.py
  hr_dms_field/tests/test_hr_dms_field.py
  hr_dms_field/views/hr_employee_view.xml
  setup/hr_dms_field/odoo/addons/hr_dms_field
  setup/hr_dms_field/setup.py
Labels: bot is merging ⏳, approved

#293 [15.0][FIX] dms: Fix smartbuttons from files and directories
  dms/models/directory.py
  dms/models/dms_file.py
  dms/views/directory.xml
Labels: bot is merging ⏳, approved

#288 [15.0][ADD] dms_field_auto_classification: New module
  dms_field_auto_classification/README.rst
  dms_field_auto_classification/__init__.py
  dms_field_auto_classification/__manifest__.py
  dms_field_auto_classification/demo/dms_classification_template_demo.xml
  dms_field_auto_classification/i18n/dms_field_auto_classification.pot
  dms_field_auto_classification/i18n/es.po
  dms_field_auto_classification/models/__init__.py
  dms_field_auto_classification/models/dms_classification_template.py
  dms_field_auto_classification/readme/CONFIGURE.rst
  dms_field_auto_classification/readme/CONTRIBUTORS.rst
  dms_field_auto_classification/readme/DESCRIPTION.rst
  dms_field_auto_classification/readme/USAGE.rst
  dms_field_auto_classification/security/ir.model.access.csv
  dms_field_auto_classification/static/description/icon.png
  dms_field_auto_classification/static/description/icon.svg
  dms_field_auto_classification/static/description/index.html
  dms_field_auto_classification/tests/__init__.py
  dms_field_auto_classification/tests/data/test.zip
  dms_field_auto_classification/tests/test_dms_field_auto_classification.py
  dms_field_auto_classification/views/dms_classification_template_views.xml
  dms_field_auto_classification/wizards/__init__.py
  dms_field_auto_classification/wizards/wizard_dms_classification.py
  dms_field_auto_classification/wizards/wizard_dms_classification_views.xml
  setup/dms_field_auto_classification/odoo/addons/dms_field_auto_classification
  setup/dms_field_auto_classification/setup.py
Labels: bot is merging ⏳, approved, ready to merge

#298 [15.0][IMP] dms_field: Disable multiple selection not currently supported
  dms_field/README.rst
  dms_field/readme/ROADMAP.rst
  dms_field/static/description/index.html
  dms_field/static/src/js/base/dms_tree_renderer.js
Labels: bot is merging ⏳, approved

#301 [16.0][FIX] dms: Fix smartbuttons from files and directories
  dms/models/directory.py
  dms/models/dms_file.py
  dms/views/directory.xml
Labels: bot is merging ⏳, approved

#302 [16.0][IMP] dms: Improve tests
  dms/tests/common.py
  dms/tests/test_benchmark.py
  dms/tests/test_directory.py
  dms/tests/test_file.py
  dms/tests/test_file_database.py
  dms/tests/test_portal.py
  dms/tests/test_storage_attachment.py
  dms/tests/test_storage_database.py
Labels: bot is merging ⏳, approved

#296 [16.0][FIX] dms: Set the correct directory_id value according to the domain to Upload button
  dms/static/src/js/views/dms_file_upload.esm.js
Labels: bot is merging ⏳, approved

#289 [15.0][FIX] dms: Improve the unlink method in base to avoid errors
  dms/models/base.py
Labels: bot is merging ⏳, approved

#305 [16.0][FIX] dms: Improve the unlink method in base to avoid errors
  dms/models/base.py
Labels: bot is merging ⏳

#297 [15.0][IMP] dms_auto_classification: Allow users with Documents: User permissions can use the wizard
  dms_auto_classification/security/ir.model.access.csv
  dms_auto_classification/tests/test_dms_auto_classification.py
  dms_auto_classification/views/dms_classification_template_views.xml
  dms_auto_classification/wizards/wizard_dms_classification_views.xml
Labels: bot is merging ⏳, approved, ready to merge

#303 [16.0][IMP] dms: Add ACLs to dms.storage for users with the basic permission + Add human_size field to directories and files
  dms/models/directory.py
  dms/models/dms_file.py
  dms/security/ir.model.access.csv
  dms/views/directory.xml
  dms/views/dms_file.xml
  dms/views/storage.xml
Labels: bot is merging ⏳, approved, ready to merge
