Repository OCA/dms, pull requests merged in 2024-06, with the labels that each got.

#342 [IMP] dms: Capture correct error to be shown at notification
  dms/static/src/js/views/dms_file_upload.esm.js
Labels: bot is merging ⏳, approved

#320 [15.0][IMP+FIX] dms_field: Add model_ref to access groups to avoid possible errors when creating directories from a template.
  dms_field/__manifest__.py
  dms_field/i18n/dms_field.pot
  dms_field/i18n/es.po
  dms_field/i18n/fr.po
  dms_field/i18n/it.po
  dms_field/models/__init__.py
  dms_field/models/dms_access_group.py
  dms_field/models/dms_field_template.py
  dms_field/tests/test_dms_field.py
  dms_field/views/dms_access_group_views.xml
  hr_dms_field/models/__init__.py
  hr_dms_field/models/hr_employee.py
  hr_dms_field/tests/test_hr_dms_field.py
Labels: bot is merging ⏳, approved, ready to merge

#345 [15.0][FIX] dms: Allow share (directories and files) without 'Contact creation' permission
  dms/__manifest__.py
  dms/security/ir.model.access.csv
  dms/tests/test_directory.py
  dms/tests/test_file.py
  dms/tests/test_file_database.py
  dms/tests/test_storage_attachment.py
  dms/views/directory.xml
  dms/views/dms_file.xml
  dms/wizards/__init__.py
  dms/wizards/wizard_dms_share.py
  dms/wizards/wizard_dms_share_views.xml
Labels: bot is merging ⏳, approved

#346 [15.0][FIX] hr_dms_field: Apply correct condition + apply .sudo() to prevent ACL error from dms.access.group
  hr_dms_field/models/hr_employee.py
Labels: bot is merging ⏳

#348 [16.0][FIX] dms_field: Use own service instead of using dialog service of component
  dms_field/static/src/views/dms_list/dms_list_renderer.esm.js
Labels: bot is merging ⏳, approved

#336 [16.0][MIG] dms_field_auto_classification: Migration to 16.0
  dms_field_auto_classification/README.rst
  dms_field_auto_classification/__init__.py
  dms_field_auto_classification/__manifest__.py
  dms_field_auto_classification/demo/dms_classification_template_demo.xml
  dms_field_auto_classification/i18n/dms_field_auto_classification.pot
  dms_field_auto_classification/i18n/es.po
  dms_field_auto_classification/models/__init__.py
  dms_field_auto_classification/models/dms_classification_template.py
  dms_field_auto_classification/readme/CONFIGURE.rst
  dms_field_auto_classification/readme/CONTRIBUTORS.rst
  dms_field_auto_classification/readme/DESCRIPTION.rst
  dms_field_auto_classification/readme/USAGE.rst
  dms_field_auto_classification/security/ir.model.access.csv
  dms_field_auto_classification/static/description/icon.png
  dms_field_auto_classification/static/description/icon.svg
  dms_field_auto_classification/static/description/index.html
  dms_field_auto_classification/tests/__init__.py
  dms_field_auto_classification/tests/data/test.zip
  dms_field_auto_classification/tests/test_dms_field_auto_classification.py
  dms_field_auto_classification/views/dms_classification_template_views.xml
  dms_field_auto_classification/wizards/__init__.py
  dms_field_auto_classification/wizards/wizard_dms_classification.py
  dms_field_auto_classification/wizards/wizard_dms_classification_views.xml
  setup/dms_field_auto_classification/odoo/addons/dms_field_auto_classification
  setup/dms_field_auto_classification/setup.py
Labels: bot is merging ⏳, approved, ready to merge

#340 [16.0][MIG] hr_dms_field: Migration to 16.0
  dms_field/tests/test_dms_field.py
  hr_dms_field/README.rst
  hr_dms_field/__init__.py
  hr_dms_field/__manifest__.py
  hr_dms_field/demo/dms_data.xml
  hr_dms_field/i18n/es.po
  hr_dms_field/i18n/hr_dms_field.pot
  hr_dms_field/models/__init__.py
  hr_dms_field/models/dms_field_template.py
  hr_dms_field/models/hr_employee.py
  hr_dms_field/models/hr_employee_public.py
  hr_dms_field/readme/CONFIGURE.rst
  hr_dms_field/readme/CONTRIBUTORS.rst
  hr_dms_field/readme/DESCRIPTION.rst
  hr_dms_field/readme/USAGE.rst
  hr_dms_field/static/description/icon.png
  hr_dms_field/static/description/index.html
  hr_dms_field/static/src/js/base/dms_list_controller.esm.js
  hr_dms_field/tests/__init__.py
  hr_dms_field/tests/test_hr_dms_field.py
  hr_dms_field/views/hr_employee_view.xml
  setup/hr_dms_field/odoo/addons/hr_dms_field
  setup/hr_dms_field/setup.py
Labels: bot is merging ⏳, approved, ready to merge
