Repository OCA/dms, pull requests merged in 2024-04, with the labels that each got.

#322 [16.0][MIG] dms_auto_classification: Migration to 16.0
  dms_auto_classification/README.rst
  dms_auto_classification/__init__.py
  dms_auto_classification/__manifest__.py
  dms_auto_classification/demo/dms_classification_template_demo.xml
  dms_auto_classification/i18n/dms_auto_classification.pot
  dms_auto_classification/i18n/es.po
  dms_auto_classification/models/__init__.py
  dms_auto_classification/models/dms_classification_template.py
  dms_auto_classification/readme/CONFIGURE.rst
  dms_auto_classification/readme/CONTRIBUTORS.rst
  dms_auto_classification/readme/DESCRIPTION.rst
  dms_auto_classification/readme/USAGE.rst
  dms_auto_classification/security/ir.model.access.csv
  dms_auto_classification/security/security.xml
  dms_auto_classification/static/description/icon.png
  dms_auto_classification/static/description/icon.svg
  dms_auto_classification/static/description/index.html
  dms_auto_classification/tests/__init__.py
  dms_auto_classification/tests/data/test.zip
  dms_auto_classification/tests/test_dms_auto_classification.py
  dms_auto_classification/views/dms_classification_template_views.xml
  dms_auto_classification/wizards/__init__.py
  dms_auto_classification/wizards/wizard_dms_classification.py
  dms_auto_classification/wizards/wizard_dms_classification_views.xml
  setup/dms_auto_classification/odoo/addons/dms_auto_classification
  setup/dms_auto_classification/setup.py
Labels: bot is merging ⏳, approved

#182 [ADD] dms_storage
  dms/models/dms_file.py
  dms_storage/README.rst
  dms_storage/__init__.py
  dms_storage/__manifest__.py
  dms_storage/models/__init__.py
  dms_storage/models/dms_file.py
  dms_storage/models/dms_storage.py
  dms_storage/readme/CONTRIBUTORS.rst
  dms_storage/readme/DESCRIPTION.rst
  dms_storage/static/description/icon.png
  dms_storage/static/description/index.html
  dms_storage/tests/__init__.py
  dms_storage/tests/test_storage.py
  dms_storage/views/dms_storage.xml
  setup/dms_storage/odoo/addons/dms_storage
  setup/dms_storage/setup.py
Labels: bot is merging ⏳

#324 [15.0][IMP] dms: Add number items (directories and files) to directory kanban view
  dms/static/src/scss/directory_kanban.scss
  dms/views/directory.xml
Labels: bot is merging ⏳, approved, ready to merge

#325 [15.0][IMP] dms_field: Add Parent directory option to templates
  dms_field/i18n/dms_field.pot
  dms_field/i18n/es.po
  dms_field/models/dms_directory.py
  dms_field/models/dms_field_template.py
  dms_field/tests/test_dms_field.py
  dms_field/views/dms_field_template_views.xml
Labels: bot is merging ⏳, approved, ready to merge

#318 [16.0][IMP] dms: Add move (change directory) action from files
  dms/__init__.py
  dms/__manifest__.py
  dms/i18n/dms.pot
  dms/i18n/es.po
  dms/models/dms_file.py
  dms/security/ir.model.access.csv
  dms/static/description/index.html
  dms/tests/test_file.py
  dms/views/dms_file.xml
  dms/wizards/__init__.py
  dms/wizards/wizard_dms_file_move.py
  dms/wizards/wizard_dms_file_move_views.xml
Labels: bot is merging ⏳, approved
