Repository OCA/dms, pull requests merged in 2025-04, with the labels that each got.

#397 [16.0][FIX] dms: Delete the file if the attachment is deleted
  dms/models/dms_file.py
  dms/models/ir_attachment.py
  dms/tests/test_storage_attachment.py
  dms/views/dms_file.xml
Labels: bot is merging ⏳

#405 [17.0][FIX] dms: Delete the file if the attachment is deleted
  dms/models/dms_file.py
  dms/models/ir_attachment.py
  dms/tests/test_storage_attachment.py
  dms/views/dms_file.xml
Labels: bot is merging ⏳

#407 [18.0][MIG] dms_user_role: Migration to 18.0
  dms_user_role/README.rst
  dms_user_role/__init__.py
  dms_user_role/__manifest__.py
  dms_user_role/i18n/dms_user_role.pot
  dms_user_role/i18n/es.po
  dms_user_role/i18n/it.po
  dms_user_role/models/__init__.py
  dms_user_role/models/dms_access_group.py
  dms_user_role/pyproject.toml
  dms_user_role/readme/CONTRIBUTORS.md
  dms_user_role/readme/DESCRIPTION.md
  dms_user_role/readme/USAGE.md
  dms_user_role/static/description/icon.png
  dms_user_role/static/description/index.html
  dms_user_role/tests/__init__.py
  dms_user_role/tests/test_dms_user_role.py
  dms_user_role/views/dms_access_group_views.xml
Labels: bot is merging ⏳, approved

#406 [18.0][FIX] dms: Show full file name in kanban view
  dms/views/dms_file.xml
Labels: bot is merging ⏳, approved, ready to merge

#411 [17.0][FIX] dms: Show short name of directories in searchpanel
  dms/models/directory.py
Labels: bot is merging ⏳

#412 [18.0][FIX] dms: Delete the file if the attachment is deleted
  dms/models/dms_file.py
  dms/models/ir_attachment.py
  dms/tests/test_storage_attachment.py
  dms/views/dms_file.xml
Labels: bot is merging ⏳

#413 [18.0][FIX] dms: Show short name of directories in searchpanel
  dms/models/directory.py
Labels: bot is merging ⏳

#414 [16.0][FIX] dms: searchpanel changes apply only to dms
  dms/static/src/js/views/search_panel.esm.js
Labels: bot is merging ⏳, approved

#415 [17.0][FIX] dms: searchpanel changes apply only to dms
  dms/static/src/js/views/search_panel.esm.js
Labels: bot is merging ⏳, approved

#418 [18.0][FIX] dms: searchpanel changes apply only to dms
  dms/static/src/js/views/search_panel.esm.js
Labels: bot is merging ⏳
